name: Compile changelogs

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  compile:
    name: "Compile changelogs"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: "Install deps"
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
          sudo apt-get install  dos2unix

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 25
          persist-credentials: false

      - name: "Compile"
        run: |
          python tools/ss13_genchangelog.py html/changelogs

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Changelogs"
          git pull origin main
          git add html/changelogs
          git commit -m "Automatic changelog compile [ci skip]" -a || true

      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@v1
        if: env.APP_PRIVATE_KEY != '' && env.APP_ID != ''
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: "Push"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.app-token-generation.outputs.token || secrets.GITHUB_TOKEN }}
